spring:
  datasource:
    url: jdbc:h2:file:/resources/h2/data/bookstore
    username: sa
    password: $51
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
hibernate:
  id:
    new_generator_mappings: true

logging.level.org.hibernate.SQL: DEBUG